# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsederhana', '0008_auto_20160112_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Picture'),
        ),
    ]
