# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 16:45
from __future__ import unicode_literals

import blogsederhana.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsederhana', '0009_auto_20160115_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=blogsederhana.models.generate_filename, verbose_name='Picture'),
        ),
    ]
