# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsederhana', '0012_auto_20160117_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
