# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsederhana', '0014_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
