# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsederhana', '0015_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Picture'),
        ),
    ]
