# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsederhana', '0016_auto_20160122_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('facebook_url', models.CharField(max_length=100)),
                ('twitter_url', models.CharField(max_length=100)),
                ('instagram_url', models.CharField(max_length=100)),
                ('github_url', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
