# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsederhana', '0017_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Picture'),
        ),
    ]
